name: vimscript / vint

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: 3.11

      - name: Install project dependencies
        run: pip install vim-vint

      - name: Run exercism/vimscript ci (runs tests) for all exercises
        run: vint .
